export const homeObjOne = {
    lightBg: false, 
    primary: true,  
    imgStart: '', 
    lightTopLine: true, 
    lightTextDesc: true, 
    buttonLabel: 'Get Started', 
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce ut placerat orci nulla pellentesque dignissim enim', 
    headline: 'LA diam sollicitudin tempor id eu nisl. ', 
    lightText: true, 
    topLine: 'Scelerisque felis imperdiet', 
    img: require ('../../images/picture-1.jpg'), 
    alt: 'Image', 
    start: '', 
};

export const homeObjTwo = {
    lightBg: true, 
    primary: false,  
    imgStart: 'Start', 
    lightTopLine: false, 
    lightTextDesc: false, 
    buttonLabel: 'Get Started', 
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce ut placerat orci nulla pellentesque dignissim enim', 
    headline: 'LA diam sollicitudin tempor id eu nisl. ', 
    lightText: false, 
    topLine: 'Scelerisque felis imperdiet', 
    img: require ('../../images/picture-1.jpg'), 
    alt: 'Image', 
    start: 'true', 
};

export const homeObjThree = {
    lightBg: false, 
    primary: true,  
    imgStart: '', 
    lightTopLine: true, 
    lightTextDesc: true, 
    buttonLabel: 'Get Started', 
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce ut placerat orci nulla pellentesque dignissim enim', 
    headline: 'LA diam sollicitudin tempor id eu nisl. ', 
    lightText: true, 
    topLine: 'Scelerisque felis imperdiet', 
    img: require ('../../images/picture-1.jpg'), 
    alt: 'Image', 
    start: '', 
};
export const homeObjFour = {
    lightBg: true, 
    primary: false,  
    imgStart: 'start', 
    lightTopLine: false, 
    lightTextDesc: false, 
    buttonLabel: 'Get Started', 
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce ut placerat orci nulla pellentesque dignissim enim', 
    headline: 'LA diam sollicitudin tempor id eu nisl. ', 
    lightText: false, 
    topLine: 'Scelerisque felis imperdiet', 
    img: require ('../../images/picture-1.jpg'), 
    alt: 'Image', 
    start: 'true', 
};